begin;
select plan(35);

select has_table('private','staff_role_assignments','live staff assignments exist');
select has_table('private','staff_role_events','staff role history exists');
select has_table('public','moderation_notes','internal notes exist');
select has_table('public','moderation_decisions','append-only decisions exist');
select has_table('public','evidence_access_events','evidence access audit exists');
select has_table('public','moderation_audit_events','internal audit exists');
select has_table('public','notification_outbox','durable outbox exists');
select has_index('private','staff_role_assignments','staff_role_assignments_active_unique','one live assignment per role');
select has_index('public','safety_reports','safety_reports_queue_idx','moderation queue is indexed');
select has_index('public','notification_outbox','notification_outbox_deduplication_key_key','outbox effects deduplicate');
select has_index('public','notification_outbox','notification_outbox_claim_idx','outbox claiming is indexed');
select ok((select relrowsecurity from pg_class where oid='public.moderation_notes'::regclass),'note RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.moderation_decisions'::regclass),'decision RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.evidence_access_events'::regclass),'evidence audit RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.notification_outbox'::regclass),'outbox RLS enabled');
select table_privs_are('public','moderation_notes','authenticated',array[]::text[],'members cannot read or write notes');
select table_privs_are('public','moderation_decisions','authenticated',array[]::text[],'members cannot read or write decisions');
select table_privs_are('public','evidence_access_events','authenticated',array[]::text[],'members cannot forge evidence access');
select table_privs_are('public','moderation_audit_events','authenticated',array[]::text[],'members cannot forge internal audit');
select table_privs_are('public','notification_outbox','authenticated',array[]::text[],'members cannot read or forge outbox');
select table_privs_are('private','staff_role_assignments','authenticated',array[]::text[],'members cannot query staff roles');
select ok(has_function_privilege('authenticated','public.get_my_staff_access()','execute'),'member can test own opaque staff access');
select ok(has_function_privilege('authenticated','public.get_moderation_report_queue(integer,timestamp with time zone,uuid)','execute'),'staff queue RPC exposed behind live checks');
select ok(has_function_privilege('authenticated','public.record_moderation_decision(uuid,text,text,text,text)','execute'),'decision RPC exposed behind live checks');
select ok(not has_function_privilege('authenticated','public.claim_notification_outbox(text,integer)','execute'),'members cannot claim outbox');
select ok(has_function_privilege('service_role','public.claim_notification_outbox(text,integer)','execute'),'worker can claim outbox');
select ok(not has_function_privilege('authenticated','private.bootstrap_first_administrator(uuid,text)','execute'),'bootstrap unavailable to API roles');
select triggers_are('public','messages',array['message_notification_outbox'],'messages enqueue transactionally');
select triggers_are('public','safety_reports',array['report_notification_outbox'],'reports enqueue transactionally');
select triggers_are('public','bookings',array['booking_conversation_after_insert','booking_notification_outbox'],'booking and outbox triggers coexist');
select col_not_null('public','notification_outbox','deduplication_key','outbox idempotency key required');
select col_not_null('public','moderation_decisions','actor_id','decision actor required');
select col_not_null('public','evidence_access_events','purpose_code','evidence purpose required');
select col_is_fk('public','moderation_decisions','actor_id','decision actor is constrained');
select col_is_fk('public','notification_outbox','recipient_id','outbox recipient is constrained');

select * from finish();
rollback;
