saveExact: true
allowBuilds:
  '@sentry/cli': false
  esbuild: true
  supabase: true
  sharp: false
  unrs-resolver: false
engineStrict: true
patchedDependencies:
  '@supabase/auth-js@2.116.0': patches/@supabase__auth-js@2.116.0.patch
