import type { Locale } from '@/lib/auth/validation';
import type { MatchingReasonCode } from '@/modules/matching/model';

export const matchingCopy = {
  fr: {
    tripMatches: 'Demandes compatibles avec ce voyage',
    requestMatches: 'Voyages compatibles avec cette demande',
    noMatches: 'Aucune correspondance compatible pour le moment.',
    explanation: 'Pourquoi cette correspondance fonctionne',
    route: 'Itinéraire exact',
    dates: 'Dates dans la fenêtre demandée',
    category: 'Catégorie acceptée',
    capacity: 'Capacité suffisante',
    capacityFit: 'Marge de capacité',
    dateFit: 'Marge totale de dates',
    algorithm: 'Version de correspondance',
    advisory:
      'Cette correspondance est indicative. La capacité n’est pas réservée.',
    previous: 'Précédent',
    next: 'Suivant',
    sender: 'Expéditeur',
    traveler: 'Voyageur',
    emailVerified: 'E-mail vérifié',
    phoneVerified: 'Téléphone vérifié',
    identityVerified: 'Identité vérifiée',
    completedJobs: 'Missions terminées',
    reviews: 'Avis',
    minutes: 'minutes',
    viewListing: 'Voir la fiche publiée',
    pagination: 'Pagination des correspondances',
    backToTrip: 'Revenir au voyage',
    backToRequest: 'Revenir à la demande',
  },
  en: {
    tripMatches: 'Matches for this trip',
    requestMatches: 'Matches for this delivery request',
    noMatches: 'No compatible matches yet.',
    explanation: 'Why this matches',
    route: 'Exact route',
    dates: 'Dates fit the requested window',
    category: 'Category accepted',
    capacity: 'Capacity sufficient',
    capacityFit: 'Capacity slack',
    dateFit: 'Total date slack',
    algorithm: 'Matching version',
    advisory: 'This match is advisory. Capacity is not reserved.',
    previous: 'Previous',
    next: 'Next',
    sender: 'Sender',
    traveler: 'Traveler',
    emailVerified: 'Email verified',
    phoneVerified: 'Phone verified',
    identityVerified: 'Identity verified',
    completedJobs: 'Completed jobs',
    reviews: 'Reviews',
    minutes: 'minutes',
    viewListing: 'View published listing',
    pagination: 'Match pagination',
    backToTrip: 'Back to trip',
    backToRequest: 'Back to delivery request',
  },
  ar: {
    tripMatches: 'طلبات متوافقة مع هذه الرحلة',
    requestMatches: 'رحلات متوافقة مع طلب الإرسال',
    noMatches: 'لا توجد مطابقات متوافقة حالياً.',
    explanation: 'سبب التوافق',
    route: 'المسار مطابق تماماً',
    dates: 'المواعيد ضمن الفترة المطلوبة',
    category: 'الفئة مقبولة',
    capacity: 'السعة كافية',
    capacityFit: 'هامش السعة',
    dateFit: 'إجمالي هامش المواعيد',
    algorithm: 'إصدار المطابقة',
    advisory: 'هذه المطابقة إرشادية ولا تحجز السعة.',
    previous: 'السابق',
    next: 'التالي',
    sender: 'المرسل',
    traveler: 'المسافر',
    emailVerified: 'البريد موثّق',
    phoneVerified: 'الهاتف موثّق',
    identityVerified: 'الهوية موثّقة',
    completedJobs: 'مهام مكتملة',
    reviews: 'التقييمات',
    minutes: 'دقيقة',
    viewListing: 'عرض الإعلان المنشور',
    pagination: 'التنقل بين صفحات المطابقات',
    backToTrip: 'العودة إلى الرحلة',
    backToRequest: 'العودة إلى طلب الإرسال',
  },
} satisfies Record<Locale, Record<string, string>>;

const reasonKeys: Record<
  MatchingReasonCode,
  'route' | 'dates' | 'category' | 'capacity'
> = {
  exact_route: 'route',
  date_window_fit: 'dates',
  category_accepted: 'category',
  capacity_sufficient: 'capacity',
};

export function reasonLabel(
  locale: Locale,
  reason: MatchingReasonCode,
): string {
  return matchingCopy[locale][reasonKeys[reason]];
}
