import type { Locale } from '@/lib/auth/validation';
import { categoryCopy } from '@/modules/trips/copy';

export const requestCopy = {
  fr: {
    myRequests: 'Mes envois',
    createRequest: 'Envoyer un objet',
    editRequest: 'Modifier la demande',
    requestDetail: 'Détails de la demande',
    publicRequest: 'Demande publiée',
    noRequests: 'Vous n’avez encore aucune demande.',
    origin: 'Départ',
    destination: 'Destination',
    earliestDeparture: 'Départ au plus tôt',
    latestDelivery: 'Livraison au plus tard',
    category: 'Catégorie',
    title: 'Titre court',
    description: 'Description',
    declaredContents: 'Contenu déclaré',
    weight: 'Poids total (kg)',
    dimensions: 'Dimensions facultatives (cm)',
    length: 'Longueur',
    width: 'Largeur',
    height: 'Hauteur',
    quantity: 'Quantité',
    fragile: 'Fragile',
    handlingNotes: 'Consignes de manutention facultatives',
    status: 'Statut',
    saveDraft: 'Enregistrer le brouillon',
    saveChanges: 'Enregistrer les modifications',
    publish: 'Publier',
    cancel: 'Annuler la demande',
    cancellationReason: 'Motif de l’annulation',
    viewPublic: 'Voir la fiche publique',
    photos: 'Photos privées de l’article',
    photoPrivacy:
      'Les photos restent privées et ne figurent pas dans la fiche publique.',
    uploadPhoto: 'Ajouter une photo',
    photoFile: 'Fichier image',
    removePhoto: 'Supprimer',
    back: 'Retour aux envois',
    sender: 'Expéditeur',
    conflict: 'Cette demande a été modifiée ailleurs. Rechargez la page.',
    failed: 'Impossible de terminer cette opération.',
    invalid: 'Vérifiez les informations de la demande.',
    invalidPhoto: 'Utilisez une image JPEG, PNG ou WebP de 5 Mo maximum.',
    timezoneHint:
      'Saisissez l’heure locale de la ville de départ et de la ville de destination.',
    draft: 'Brouillon',
    published: 'Publiée',
    cancelled: 'Annulée',
    expired: 'Expirée',
    yes: 'Oui',
    no: 'Non',
  },
  en: {
    myRequests: 'My delivery requests',
    createRequest: 'Create request',
    editRequest: 'Edit request',
    requestDetail: 'Request details',
    publicRequest: 'Published request',
    noRequests: 'You do not have any delivery requests yet.',
    origin: 'Origin',
    destination: 'Destination',
    earliestDeparture: 'Earliest departure',
    latestDelivery: 'Latest delivery',
    category: 'Category',
    title: 'Short title',
    description: 'Description',
    declaredContents: 'Declared contents',
    weight: 'Total weight (kg)',
    dimensions: 'Optional dimensions (cm)',
    length: 'Length',
    width: 'Width',
    height: 'Height',
    quantity: 'Quantity',
    fragile: 'Fragile',
    handlingNotes: 'Optional handling notes',
    status: 'Status',
    saveDraft: 'Save draft',
    saveChanges: 'Save changes',
    publish: 'Publish',
    cancel: 'Cancel request',
    cancellationReason: 'Cancellation reason',
    viewPublic: 'View public listing',
    photos: 'Private item photos',
    photoPrivacy:
      'Photos stay private and are excluded from the public listing.',
    uploadPhoto: 'Add photo',
    photoFile: 'Photo file',
    removePhoto: 'Remove',
    back: 'Back to delivery requests',
    sender: 'Sender',
    conflict: 'This request changed elsewhere. Reload the page.',
    failed: 'Unable to complete this request.',
    invalid: 'Check the delivery request information.',
    invalidPhoto: 'Use a JPEG, PNG or WebP image up to 5 MB.',
    timezoneHint: 'Enter local time for the origin city and destination city.',
    draft: 'Draft',
    published: 'Published',
    cancelled: 'Cancelled',
    expired: 'Expired',
    yes: 'Yes',
    no: 'No',
  },
  ar: {
    myRequests: 'طلبات الإرسال',
    createRequest: 'إنشاء طلب',
    editRequest: 'تعديل الطلب',
    requestDetail: 'تفاصيل الطلب',
    publicRequest: 'طلب منشور',
    noRequests: 'ليس لديك طلبات إرسال بعد.',
    origin: 'مدينة الانطلاق',
    destination: 'الوجهة',
    earliestDeparture: 'أقرب موعد للانطلاق',
    latestDelivery: 'آخر موعد للتسليم',
    category: 'الفئة',
    title: 'عنوان مختصر',
    description: 'الوصف',
    declaredContents: 'المحتويات المصرح بها',
    weight: 'الوزن الإجمالي بالكيلوغرام',
    dimensions: 'الأبعاد الاختيارية بالسنتيمتر',
    length: 'الطول',
    width: 'العرض',
    height: 'الارتفاع',
    quantity: 'الكمية',
    fragile: 'قابل للكسر',
    handlingNotes: 'تعليمات مناولة اختيارية',
    status: 'الحالة',
    saveDraft: 'حفظ المسودة',
    saveChanges: 'حفظ التغييرات',
    publish: 'نشر',
    cancel: 'إلغاء الطلب',
    cancellationReason: 'سبب الإلغاء',
    viewPublic: 'عرض الطلب العام',
    photos: 'صور خاصة للغرض',
    photoPrivacy: 'تبقى الصور خاصة ولا تظهر في العرض العام.',
    uploadPhoto: 'إضافة صورة',
    photoFile: 'ملف الصورة',
    removePhoto: 'حذف',
    back: 'العودة إلى الطلبات',
    sender: 'المرسل',
    conflict: 'تم تعديل الطلب في مكان آخر. أعد تحميل الصفحة.',
    failed: 'تعذر إكمال هذا الطلب.',
    invalid: 'تحقق من معلومات طلب الإرسال.',
    invalidPhoto: 'استخدم صورة JPEG أو PNG أو WebP بحجم أقصى 5 ميغابايت.',
    timezoneHint: 'أدخل الوقت المحلي لمدينة الانطلاق ومدينة الوجهة.',
    draft: 'مسودة',
    published: 'منشور',
    cancelled: 'ملغى',
    expired: 'منتهي',
    yes: 'نعم',
    no: 'لا',
  },
} satisfies Record<Locale, Record<string, string>>;

export function requestCategoryLabel(locale: Locale, code: string) {
  return (
    categoryCopy[locale][code as keyof (typeof categoryCopy)[Locale]] ?? code
  );
}
