import type { Locale } from '@/lib/auth/validation';

const en = {
  messages: 'Messages',
  inbox: 'Booking messages',
  inboxHint: 'Private conversations linked to your bookings.',
  empty: 'No booking conversations yet.',
  emptyHint: 'A private conversation appears when you propose a booking.',
  open: 'Open conversation',
  back: 'Back to messages',
  booking: 'View booking',
  composer: 'Write a message',
  send: 'Send message',
  closed: 'This booking is closed. You can still read its message history.',
  refresh: 'Refresh messages',
  unread: 'unread',
  report: 'Report a concern',
  reportMessage: 'Report this message',
  reason: 'Reason',
  description: 'What happened?',
  submitReport: 'Submit report',
  reportHint:
    'Flyco records your report privately. The other participant cannot see it.',
  reportSent: 'Your report was submitted.',
  sent: 'Message sent.',
  messageLimit: 'Maximum 2,000 characters. Plain text only.',
  harassment: 'Harassment',
  suspicious_behavior: 'Suspicious behavior',
  prohibited_item: 'Prohibited item concern',
  scam_fraud: 'Scam or fraud concern',
  unsafe_conduct: 'Unsafe conduct',
  inappropriate_content: 'Inappropriate content',
  other: 'Other',
};
type Copy = typeof en;
export const messagingCopy: Record<Locale, Copy> = {
  en,
  fr: {
    messages: 'Messages',
    inbox: 'Messages de réservation',
    inboxHint: 'Conversations privées liées à vos réservations.',
    empty: 'Aucune conversation pour le moment.',
    emptyHint:
      'Une conversation privée apparaît après une proposition de réservation.',
    open: 'Ouvrir la conversation',
    back: 'Retour aux messages',
    booking: 'Voir la réservation',
    composer: 'Écrire un message',
    send: 'Envoyer',
    closed: 'Cette réservation est clôturée. Son historique reste consultable.',
    refresh: 'Actualiser',
    unread: 'non lus',
    report: 'Signaler un problème',
    reportMessage: 'Signaler ce message',
    reason: 'Motif',
    description: "Que s'est-il passé ?",
    submitReport: 'Envoyer le signalement',
    reportHint:
      "Flyco conserve ce signalement de façon privée. L'autre participant ne peut pas le voir.",
    reportSent: 'Votre signalement a été envoyé.',
    sent: 'Message envoyé.',
    messageLimit: '2 000 caractères maximum. Texte brut uniquement.',
    harassment: 'Harcèlement',
    suspicious_behavior: 'Comportement suspect',
    prohibited_item: 'Objet interdit ou dangereux',
    scam_fraud: 'Suspicion de fraude',
    unsafe_conduct: 'Comportement dangereux',
    inappropriate_content: 'Contenu inapproprié',
    other: 'Autre',
  },
  ar: {
    messages: 'الرسائل',
    inbox: 'رسائل الحجوزات',
    inboxHint: 'محادثات خاصة مرتبطة بحجوزاتك.',
    empty: 'لا توجد محادثات حجز بعد.',
    emptyHint: 'تظهر محادثة خاصة عند اقتراح حجز.',
    open: 'افتح المحادثة',
    back: 'العودة إلى الرسائل',
    booking: 'عرض الحجز',
    composer: 'اكتب رسالة',
    send: 'إرسال',
    closed: 'هذا الحجز مغلق. ما زال بإمكانك قراءة سجل الرسائل.',
    refresh: 'تحديث الرسائل',
    unread: 'غير مقروءة',
    report: 'الإبلاغ عن مشكلة',
    reportMessage: 'الإبلاغ عن هذه الرسالة',
    reason: 'السبب',
    description: 'ماذا حدث؟',
    submitReport: 'إرسال البلاغ',
    reportHint: 'تحتفظ فلايكو ببلاغك بشكل خاص. لا يمكن للمشارك الآخر رؤيته.',
    reportSent: 'تم إرسال بلاغك.',
    sent: 'تم إرسال الرسالة.',
    messageLimit: 'الحد الأقصى 2000 حرف. نص عادي فقط.',
    harassment: 'مضايقة',
    suspicious_behavior: 'سلوك مريب',
    prohibited_item: 'مخاوف بشأن غرض محظور',
    scam_fraud: 'اشتباه في احتيال',
    unsafe_conduct: 'سلوك غير آمن',
    inappropriate_content: 'محتوى غير لائق',
    other: 'سبب آخر',
  },
};
