import type { Locale } from '@/lib/auth/validation';

export const tripCopy = {
  fr: {
    myTrips: 'Mes voyages',
    createTrip: 'Créer un voyage',
    editTrip: 'Modifier le voyage',
    tripDetail: 'Détails du voyage',
    publicTrip: 'Voyage publié',
    noTrips: 'Vous n’avez encore aucun voyage.',
    origin: 'Départ',
    destination: 'Destination',
    departure: 'Date et heure de départ',
    arrival: 'Date et heure d’arrivée prévue',
    capacity: 'Capacité disponible (kg)',
    categories: 'Catégories acceptées',
    status: 'Statut',
    version: 'Version',
    saveDraft: 'Enregistrer le brouillon',
    saveChanges: 'Enregistrer les modifications',
    publish: 'Publier',
    cancel: 'Annuler le voyage',
    cancellationReason: 'Motif de l’annulation',
    viewPublic: 'Voir la fiche publique',
    back: 'Retour aux voyages',
    timezoneHint:
      'Saisissez l’heure locale de chaque ville. Les heures inexistantes ou ambiguës lors d’un changement d’heure sont refusées.',
    conflict: 'Ce voyage a été modifié ailleurs. Rechargez la page.',
    failed: 'Impossible de terminer cette opération.',
    invalid: 'Vérifiez les informations du voyage.',
    traveler: 'Voyageur',
    trust: 'Indicateurs de confiance',
    emailVerified: 'E-mail vérifié',
    identityVerified: 'Identité vérifiée',
    completedJobs: 'Voyages terminés',
    reviews: 'Avis',
    draft: 'Brouillon',
    published: 'Publié',
    cancelled: 'Annulé',
    expired: 'Expiré',
    completed: 'Terminé',
  },
  en: {
    myTrips: 'My trips',
    createTrip: 'Create trip',
    editTrip: 'Edit trip',
    tripDetail: 'Trip details',
    publicTrip: 'Published trip',
    noTrips: 'You do not have any trips yet.',
    origin: 'Origin',
    destination: 'Destination',
    departure: 'Departure date and time',
    arrival: 'Expected arrival date and time',
    capacity: 'Available capacity (kg)',
    categories: 'Accepted categories',
    status: 'Status',
    version: 'Version',
    saveDraft: 'Save draft',
    saveChanges: 'Save changes',
    publish: 'Publish',
    cancel: 'Cancel trip',
    cancellationReason: 'Cancellation reason',
    viewPublic: 'View public listing',
    back: 'Back to trips',
    timezoneHint:
      'Enter each city’s local time. Missing or ambiguous daylight-saving times are rejected.',
    conflict: 'This trip changed elsewhere. Reload the page.',
    failed: 'Unable to complete this request.',
    invalid: 'Check the trip information.',
    traveler: 'Traveler',
    trust: 'Trust indicators',
    emailVerified: 'Email verified',
    identityVerified: 'Identity verified',
    completedJobs: 'Completed traveler jobs',
    reviews: 'Reviews',
    draft: 'Draft',
    published: 'Published',
    cancelled: 'Cancelled',
    expired: 'Expired',
    completed: 'Completed',
  },
  ar: {
    myTrips: 'رحلاتي',
    createTrip: 'إنشاء رحلة',
    editTrip: 'تعديل الرحلة',
    tripDetail: 'تفاصيل الرحلة',
    publicTrip: 'رحلة منشورة',
    noTrips: 'ليس لديك رحلات بعد.',
    origin: 'مدينة الانطلاق',
    destination: 'الوجهة',
    departure: 'تاريخ ووقت الانطلاق',
    arrival: 'تاريخ ووقت الوصول المتوقع',
    capacity: 'السعة المتاحة بالكيلوغرام',
    categories: 'الفئات المقبولة',
    status: 'الحالة',
    version: 'الإصدار',
    saveDraft: 'حفظ المسودة',
    saveChanges: 'حفظ التغييرات',
    publish: 'نشر',
    cancel: 'إلغاء الرحلة',
    cancellationReason: 'سبب الإلغاء',
    viewPublic: 'عرض الرحلة العامة',
    back: 'العودة إلى الرحلات',
    timezoneHint:
      'أدخل الوقت المحلي لكل مدينة. تُرفض الأوقات غير الموجودة أو الملتبسة عند تغيير التوقيت.',
    conflict: 'تم تعديل الرحلة في مكان آخر. أعد تحميل الصفحة.',
    failed: 'تعذر إكمال هذا الطلب.',
    invalid: 'تحقق من معلومات الرحلة.',
    traveler: 'المسافر',
    trust: 'مؤشرات الثقة',
    emailVerified: 'البريد موثّق',
    identityVerified: 'الهوية موثّقة',
    completedJobs: 'رحلات مكتملة',
    reviews: 'التقييمات',
    draft: 'مسودة',
    published: 'منشورة',
    cancelled: 'ملغاة',
    expired: 'منتهية',
    completed: 'مكتملة',
  },
} satisfies Record<Locale, Record<string, string>>;

export const categoryCopy = {
  fr: {
    documents: 'Documents',
    clothing: 'Vêtements',
    electronics: 'Électronique',
    packaged_goods: 'Produits emballés',
    other_personal_items: 'Autres effets personnels autorisés',
  },
  en: {
    documents: 'Documents',
    clothing: 'Clothing',
    electronics: 'Electronics',
    packaged_goods: 'Packaged goods',
    other_personal_items: 'Other allowed personal items',
  },
  ar: {
    documents: 'مستندات',
    clothing: 'ملابس',
    electronics: 'إلكترونيات',
    packaged_goods: 'سلع مغلفة',
    other_personal_items: 'أغراض شخصية أخرى مسموحة',
  },
} satisfies Record<Locale, Record<string, string>>;

export function categoryLabel(locale: Locale, code: string): string {
  return (
    categoryCopy[locale][code as keyof (typeof categoryCopy)[Locale]] ?? code
  );
}
