import type { Locale } from '@/lib/auth/validation';

const en = {
  home: 'Home',
  requests: 'My requests',
  trips: 'My trips',
  bookings: 'Bookings',
  messages: 'Messages',
  account: 'Profile',
  navigation: 'Main navigation',
  language: 'Language',
  skip: 'Skip to content',
  send: 'Send an item',
  carry: 'I’m traveling',
  eyebrow: 'A little space. A new connection.',
  headline: 'Going your way.',
  headlineSecond: 'Bringing us closer.',
  intro:
    'Send items with travelers already going your way. Connect across France and Morocco, with one account for sending and carrying.',
  corridor: 'France ↔ Morocco',
  how: 'Small items. Shared journeys.',
  howIntro:
    'A simple way to connect what needs to go with someone already going.',
  senderTitle: 'Something to send?',
  senderBody:
    'Tell us where it’s going, when it needs to arrive and what’s inside.',
  travelerTitle: 'Space in your luggage?',
  travelerBody:
    'Share your route, travel dates and the weight you’re happy to carry.',
  connectTitle: 'Find the right fit',
  connectBody:
    'Compare compatible routes and dates, then send a booking proposal. Capacity is held when the traveler accepts.',
  trustTitle: 'Know who you’re connecting with',
  trustBody:
    'Public profiles and clear verification indicators help you make an informed choice. A match is an introduction, not a delivery guarantee.',
  stage:
    'Flyco is in preview. Booking proposals are available; payments and delivery handoff are not available yet.',
  activity: 'Your next journey starts here',
  activityBody: 'Send something, share a trip or pick up where you left off.',
  requestHint: 'Manage your items and find travelers.',
  tripHint: 'Share your route and explore compatible items.',
  bookingHint: 'Follow proposals and reserved capacity.',
  footer: 'A little closer, wherever you’re going.',
  route: 'Your route',
  dates: 'Your dates',
  item: 'Your item',
  space: 'Your carrying space',
  routeHint: 'Choose the cities at each end of the journey.',
  datesHint:
    'Enter local time for each city. We’ll keep the timezones aligned.',
  itemHint:
    'Be specific about the contents. You can add photos and review before publishing.',
  spaceHint: 'Only select categories you’re comfortable carrying.',
  reviewHint:
    'Review your details before publishing. You can add up to five private item photos below.',
  pending: 'Please wait…',
  saved: 'Your changes have been saved.',
  errorTitle: 'Something didn’t load',
  errorBody:
    'Please try again. If you submitted an action, check its current status before repeating it.',
  retry: 'Try again',
  notFound: 'This page isn’t available',
  notFoundBody:
    'It may no longer be available, or you may need to sign in to view it.',
  loading: 'Loading your next step',
  emptyTrips:
    'Your next trip could help someone send an item. Add your route to get started.',
  emptyRequests:
    'Tell us about your item and its destination. We’ll show travelers whose plans fit.',
  emptyBookings:
    'Booking proposals appear here once you connect through a compatible trip. Start with your requests or trips.',
  emptyMatches:
    'There isn’t a suitable match right now. Check your route and dates, or come back when more members have shared their plans.',
  cancelHint:
    'This action cannot be undone. Any capacity reserved by this booking will be released.',
  cancelListingHint:
    'This listing will no longer be available for new matches. This action cannot be undone.',
  confirm: 'Confirm your choice',
  keep: 'Keep this',
  security: 'Account security',
  personal: 'Your profile',
  privateHint:
    'Your legal name and phone are private. Your display name, bio and city can appear on your public profile.',
  photoHint: 'JPEG, PNG or WebP · up to 2 MiB',
  phoneHint:
    'Include your country code, for example +33 or +212. SMS verification is not available yet.',
  changeEmail: 'Change email address',
  memberSince: 'Member since',
  notVerified: 'Not verified yet',
  verificationUnavailable:
    'Identity checks are not available yet. Starting a request does not verify your identity.',
  not_started: 'Not started',
  pendingVerification: 'Awaiting verification',
  requires_input: 'More information needed',
  under_review: 'Under review',
  verified: 'Verified',
  rejected: 'Not approved',
  expired: 'Expired',
  revoked: 'Revoked',
  cancelled: 'Cancelled',
  authIntro: 'One account. Two ways to connect.',
  signupHint: 'Create your account to send items or share your journey.',
  loginHint: 'Welcome back. Your journeys are waiting.',
  passwordHint: 'Use at least 12 characters.',
  resetHint:
    'We’ll email you a link if an account can receive a password reset.',
  emailHint:
    'Open the link in your email to continue. Check your spam folder too. You can open it on another device.',
  already: 'Already a member?',
  newMember: 'New to Flyco?',
  backLogin: 'Back to sign in',
  confirmTitle: 'Continue with Flyco',
  confirmBody: 'Use the button below to confirm your email request securely.',
  confirmAction: 'Continue securely',
  invalidConfirmation: 'This confirmation link is invalid or expired.',
  unavailable: 'Your account is currently unavailable. Please contact support.',
  timeline: 'Booking progress',
  waiting: 'Waiting for the traveler',
  acceptedHint:
    'The traveler has accepted. Capacity is reserved for this item.',
  terminalHint: 'This proposal is closed. No capacity is reserved for it.',
  weight: 'Item weight',
  offered: 'Offered capacity',
  capacity: 'Available capacity',
  proposedAt: 'Proposal sent',
  acceptedAt: 'Accepted',
  closedAt: 'Closed',
  utc: 'Times shown in UTC',
};
export type UiCopy = typeof en;
export const uiCopy: Record<Locale, UiCopy> = {
  en,
  fr: {
    home: 'Accueil',
    requests: 'Mes envois',
    trips: 'Mes voyages',
    bookings: 'Réservations',
    messages: 'Messages',
    account: 'Profil',
    navigation: 'Navigation principale',
    language: 'Langue',
    skip: 'Aller au contenu',
    send: 'Envoyer un objet',
    carry: 'Je voyage',
    eyebrow: 'Un peu de place. Un nouveau lien.',
    headline: 'Sur votre chemin.',
    headlineSecond: 'Plus proches, ensemble.',
    intro:
      'Confiez vos objets à des voyageurs qui vont dans la même direction. Entre la France et le Maroc, un seul compte pour envoyer et transporter.',
    corridor: 'France ↔ Maroc',
    how: 'Petits objets. Voyages partagés.',
    howIntro: 'Reliez ce qui doit partir à quelqu’un qui fait déjà le trajet.',
    senderTitle: 'Un objet à envoyer ?',
    senderBody: 'Indiquez sa destination, ses dates et ce qu’il contient.',
    travelerTitle: 'De la place dans vos bagages ?',
    travelerBody:
      'Partagez votre itinéraire, vos dates et le poids que vous pouvez transporter.',
    connectTitle: 'Trouvez le bon voyage',
    connectBody:
      'Comparez les itinéraires et les dates compatibles, puis proposez une réservation. La capacité est réservée après acceptation du voyageur.',
    trustTitle: 'Sachez avec qui vous échangez',
    trustBody:
      'Les profils publics et les indicateurs de vérification vous aident à choisir. Une correspondance est une mise en relation, pas une garantie de livraison.',
    stage:
      'Flyco est en avant-première. Les propositions de réservation sont disponibles ; les paiements et la remise des objets ne le sont pas encore.',
    activity: 'Votre prochain voyage commence ici',
    activityBody:
      'Envoyez un objet, partagez un voyage ou reprenez votre activité.',
    requestHint: 'Gérez vos objets et trouvez des voyageurs.',
    tripHint: 'Partagez votre trajet et découvrez les objets compatibles.',
    bookingHint: 'Suivez vos propositions et la capacité réservée.',
    footer: 'Un peu plus proches, où que vous alliez.',
    route: 'Votre itinéraire',
    dates: 'Vos dates',
    item: 'Votre objet',
    space: 'Votre capacité',
    routeHint: 'Choisissez les villes de départ et d’arrivée.',
    datesHint:
      'Saisissez l’heure locale de chaque ville. Nous gérons les fuseaux horaires.',
    itemHint:
      'Décrivez précisément le contenu. Vous pourrez ajouter des photos et vérifier avant de publier.',
    spaceHint:
      'Choisissez uniquement les catégories que vous acceptez de transporter.',
    reviewHint:
      'Vérifiez les informations avant de publier. Ajoutez jusqu’à cinq photos privées ci-dessous.',
    pending: 'Un instant…',
    saved: 'Vos modifications ont été enregistrées.',
    errorTitle: 'Le chargement a échoué',
    errorBody:
      'Réessayez. Si vous avez envoyé une demande, vérifiez son état avant de la répéter.',
    retry: 'Réessayer',
    notFound: 'Cette page n’est pas disponible',
    notFoundBody:
      'Elle n’est peut-être plus disponible, ou vous devez vous connecter pour la consulter.',
    loading: 'Chargement en cours',
    emptyTrips:
      'Votre prochain voyage peut aider quelqu’un à envoyer un objet. Ajoutez votre itinéraire pour commencer.',
    emptyRequests:
      'Décrivez votre objet et sa destination. Nous afficherons les voyageurs compatibles.',
    emptyBookings:
      'Vos propositions apparaîtront ici après une mise en relation. Commencez par vos envois ou vos voyages.',
    emptyMatches:
      'Aucune correspondance pour le moment. Vérifiez les villes et les dates, ou revenez lorsque de nouveaux membres auront partagé leurs projets.',
    cancelHint:
      'Cette action est définitive. La capacité réservée par cette réservation sera libérée.',
    cancelListingHint:
      'Cette annonce ne sera plus proposée aux nouveaux contacts. Cette action est définitive.',
    confirm: 'Confirmez votre choix',
    keep: 'Conserver',
    security: 'Sécurité du compte',
    personal: 'Votre profil',
    privateHint:
      'Vos nom, prénom et téléphone restent privés. Votre nom affiché, votre présentation et votre ville peuvent apparaître sur votre profil public.',
    photoHint: 'JPEG, PNG ou WebP · 2 Mio maximum',
    phoneHint:
      'Incluez l’indicatif du pays, par exemple +33 ou +212. La vérification par SMS n’est pas encore disponible.',
    changeEmail: 'Modifier l’adresse e-mail',
    memberSince: 'Membre depuis',
    notVerified: 'Pas encore vérifié',
    verificationUnavailable:
      'La vérification d’identité n’est pas encore disponible. Une demande ne vérifie pas votre identité.',
    not_started: 'Non commencée',
    pendingVerification: 'En attente de vérification',
    requires_input: 'Informations complémentaires requises',
    under_review: 'En cours d’examen',
    verified: 'Vérifiée',
    rejected: 'Non approuvée',
    expired: 'Expirée',
    revoked: 'Révoquée',
    cancelled: 'Annulée',
    authIntro: 'Un compte. Deux façons de se rapprocher.',
    signupHint:
      'Créez votre compte pour envoyer des objets ou partager votre voyage.',
    loginHint: 'Heureux de vous retrouver. Vos voyages vous attendent.',
    passwordHint: 'Utilisez au moins 12 caractères.',
    resetHint:
      'Nous vous enverrons un lien si un compte peut recevoir une réinitialisation.',
    emailHint:
      'Ouvrez le lien reçu par e-mail pour continuer. Vérifiez aussi les indésirables. Le lien fonctionne sur un autre appareil.',
    already: 'Déjà membre ?',
    newMember: 'Nouveau sur Flyco ?',
    backLogin: 'Retour à la connexion',
    confirmTitle: 'Continuer avec Flyco',
    confirmBody:
      'Utilisez le bouton ci-dessous pour confirmer votre demande en toute sécurité.',
    confirmAction: 'Continuer en toute sécurité',
    invalidConfirmation: 'Ce lien de confirmation est invalide ou a expiré.',
    unavailable:
      'Votre compte est actuellement indisponible. Contactez l’assistance.',
    timeline: 'Suivi de la réservation',
    waiting: 'En attente du voyageur',
    acceptedHint:
      'Le voyageur a accepté. La capacité est réservée pour cet objet.',
    terminalHint:
      'Cette proposition est clôturée. Aucune capacité n’est réservée.',
    weight: 'Poids de l’objet',
    offered: 'Capacité proposée',
    capacity: 'Capacité disponible',
    proposedAt: 'Proposition envoyée',
    acceptedAt: 'Acceptée',
    closedAt: 'Clôturée',
    utc: 'Heures affichées en UTC',
  },
  ar: {
    home: 'الرئيسية',
    requests: 'إرسالياتي',
    trips: 'رحلاتي',
    bookings: 'الحجوزات',
    messages: 'الرسائل',
    account: 'حسابي',
    navigation: 'التنقل الرئيسي',
    language: 'اللغة',
    skip: 'انتقل إلى المحتوى',
    send: 'أرسل غرضاً',
    carry: 'أنا مسافر',
    eyebrow: 'مساحة صغيرة. صلة جديدة.',
    headline: 'على طريقك.',
    headlineSecond: 'أقرب إلى بعضنا.',
    intro:
      'أرسل أغراضك مع مسافرين يتجهون إلى وجهتك. تواصل بين فرنسا والمغرب بحساب واحد للإرسال والنقل.',
    corridor: 'فرنسا ↔ المغرب',
    how: 'أغراض صغيرة. رحلات مشتركة.',
    howIntro: 'نصل ما يحتاج إلى السفر بمن يسافر بالفعل.',
    senderTitle: 'هل تريد إرسال غرض؟',
    senderBody: 'حدد الوجهة والتواريخ وما يحتويه الغرض.',
    travelerTitle: 'هل لديك مساحة في أمتعتك؟',
    travelerBody: 'شارك مسارك ومواعيد سفرك والوزن الذي يمكنك حمله.',
    connectTitle: 'اعثر على الرحلة المناسبة',
    connectBody:
      'قارن المسارات والمواعيد المتوافقة ثم اقترح حجزاً. تُحجز السعة عندما يقبل المسافر.',
    trustTitle: 'تعرّف على من تتواصل معه',
    trustBody:
      'تساعدك الملفات العامة ومؤشرات التحقق الواضحة على الاختيار. المطابقة وسيلة للتواصل وليست ضماناً للتسليم.',
    stage:
      'فلايكو في المرحلة التجريبية. تتوفر اقتراحات الحجز، لكن الدفع وتسليم الأغراض غير متاحين بعد.',
    activity: 'رحلتك القادمة تبدأ هنا',
    activityBody: 'أرسل غرضاً أو شارك رحلة أو تابع نشاطك.',
    requestHint: 'أدر أغراضك واعثر على مسافرين.',
    tripHint: 'شارك مسارك واستكشف الأغراض المتوافقة.',
    bookingHint: 'تابع الاقتراحات والسعة المحجوزة.',
    footer: 'أقرب قليلاً، أينما كانت وجهتك.',
    route: 'مسارك',
    dates: 'مواعيدك',
    item: 'غرضك',
    space: 'سعتك المتاحة',
    routeHint: 'اختر مدينتي المغادرة والوصول.',
    datesHint: 'أدخل التوقيت المحلي لكل مدينة. سنراعي المناطق الزمنية.',
    itemHint: 'صف المحتويات بدقة. يمكنك إضافة الصور والمراجعة قبل النشر.',
    spaceHint: 'اختر فقط الفئات التي ترغب في حملها.',
    reviewHint: 'راجع التفاصيل قبل النشر. يمكنك إضافة خمس صور خاصة أدناه.',
    pending: 'لحظة من فضلك…',
    saved: 'تم حفظ التغييرات.',
    errorTitle: 'تعذر تحميل الصفحة',
    errorBody: 'حاول مجدداً. إذا أرسلت طلباً، تحقق من حالته قبل تكراره.',
    retry: 'حاول مجدداً',
    notFound: 'هذه الصفحة غير متاحة',
    notFoundBody: 'قد تكون غير متاحة حالياً، أو تحتاج إلى تسجيل الدخول لعرضها.',
    loading: 'جارٍ التحميل',
    emptyTrips: 'قد تساعد رحلتك القادمة شخصاً على إرسال غرض. أضف مسارك للبدء.',
    emptyRequests: 'صف غرضك ووجهته. سنعرض المسافرين المتوافقين.',
    emptyBookings:
      'تظهر اقتراحات الحجز هنا بعد العثور على رحلة متوافقة. ابدأ بإرسالياتك أو رحلاتك.',
    emptyMatches:
      'لا توجد مطابقة مناسبة الآن. راجع المسار والمواعيد أو عُد عندما يشارك أعضاء آخرون خططهم.',
    cancelHint:
      'لا يمكن التراجع عن هذا الإجراء. ستُحرر السعة المحجوزة لهذا الحجز.',
    cancelListingHint:
      'لن يظهر هذا الإعلان للمطابقات الجديدة. لا يمكن التراجع عن هذا الإجراء.',
    confirm: 'أكد اختيارك',
    keep: 'احتفظ به',
    security: 'أمان الحساب',
    personal: 'ملفك الشخصي',
    privateHint:
      'اسمك القانوني ورقم هاتفك خاصان. قد يظهر اسمك المعروض ونبذتك ومدينتك في ملفك العام.',
    photoHint: 'JPEG أو PNG أو WebP · حتى 2 ميبيبايت',
    phoneHint:
      'أضف رمز البلد مثل ‎+33 أو ‎+212. التحقق عبر الرسائل القصيرة غير متاح بعد.',
    changeEmail: 'تغيير البريد الإلكتروني',
    memberSince: 'عضو منذ',
    notVerified: 'لم يتم التحقق بعد',
    verificationUnavailable:
      'التحقق من الهوية غير متاح بعد. بدء الطلب لا يعني توثيق هويتك.',
    not_started: 'لم يبدأ',
    pendingVerification: 'بانتظار التحقق',
    requires_input: 'معلومات إضافية مطلوبة',
    under_review: 'قيد المراجعة',
    verified: 'موثّق',
    rejected: 'غير معتمد',
    expired: 'منتهي',
    revoked: 'مسحوب',
    cancelled: 'ملغى',
    authIntro: 'حساب واحد. طريقتان للتواصل.',
    signupHint: 'أنشئ حسابك لإرسال الأغراض أو مشاركة رحلتك.',
    loginHint: 'مرحباً بعودتك. رحلاتك بانتظارك.',
    passwordHint: 'استخدم 12 حرفاً على الأقل.',
    resetHint: 'سنرسل رابطاً إذا كان الحساب مؤهلاً لإعادة تعيين كلمة المرور.',
    emailHint:
      'افتح الرابط في بريدك للمتابعة. تحقق أيضاً من البريد غير المرغوب فيه. يمكنك فتح الرابط على جهاز آخر.',
    already: 'لديك حساب؟',
    newMember: 'جديد على فلايكو؟',
    backLogin: 'العودة إلى تسجيل الدخول',
    confirmTitle: 'المتابعة مع فلايكو',
    confirmBody: 'استخدم الزر أدناه لتأكيد طلبك بأمان.',
    confirmAction: 'المتابعة بأمان',
    invalidConfirmation: 'رابط التأكيد غير صالح أو منتهي الصلاحية.',
    unavailable: 'حسابك غير متاح حالياً. يرجى التواصل مع الدعم.',
    timeline: 'تقدم الحجز',
    waiting: 'بانتظار المسافر',
    acceptedHint: 'قبل المسافر الطلب. السعة محجوزة لهذا الغرض.',
    terminalHint: 'هذا الاقتراح مغلق ولا يحجز أي سعة.',
    weight: 'وزن الغرض',
    offered: 'السعة المعروضة',
    capacity: 'السعة المتاحة',
    proposedAt: 'أُرسل الاقتراح',
    acceptedAt: 'تم القبول',
    closedAt: 'أُغلق',
    utc: 'الأوقات معروضة بتوقيت UTC',
  },
};
