import type { Locale } from '@/lib/auth/validation';

export const bookingCopy = {
  fr: {
    bookings: 'Mes réservations',
    booking: 'Réservation',
    noBookings: 'Aucune réservation pour le moment.',
    propose: 'Proposer la réservation',
    incoming: 'Proposition reçue',
    outgoing: 'Proposition envoyée',
    accepted: 'Acceptée',
    proposed: 'Proposée',
    rejected: 'Refusée',
    cancelled: 'Annulée',
    expired: 'Expirée',
    accept: 'Accepter',
    reject: 'Refuser',
    cancel: 'Annuler',
    reason: 'Motif de l’annulation',
    reserved: 'Poids réservé',
    available: 'Capacité disponible',
    offered: 'Capacité proposée',
    expires: 'Expire le',
    counterparty: 'Autre participant',
    timeline: 'État',
    view: 'Voir la réservation',
    back: 'Retour aux réservations',
    capacityNotice: 'La capacité est réservée uniquement après acceptation.',
  },
  en: {
    bookings: 'My bookings',
    booking: 'Booking',
    noBookings: 'No bookings yet.',
    propose: 'Propose booking',
    incoming: 'Incoming proposal',
    outgoing: 'Sent proposal',
    accepted: 'Accepted',
    proposed: 'Proposed',
    rejected: 'Rejected',
    cancelled: 'Cancelled',
    expired: 'Expired',
    accept: 'Accept',
    reject: 'Reject',
    cancel: 'Cancel',
    reason: 'Cancellation reason',
    reserved: 'Reserved weight',
    available: 'Available capacity',
    offered: 'Offered capacity',
    expires: 'Expires',
    counterparty: 'Counterparty',
    timeline: 'Status',
    view: 'View booking',
    back: 'Back to bookings',
    capacityNotice: 'Capacity is reserved only after acceptance.',
  },
  ar: {
    bookings: 'حجوزاتي',
    booking: 'الحجز',
    noBookings: 'لا توجد حجوزات حالياً.',
    propose: 'اقتراح حجز',
    incoming: 'اقتراح وارد',
    outgoing: 'اقتراح مُرسل',
    accepted: 'مقبول',
    proposed: 'مقترح',
    rejected: 'مرفوض',
    cancelled: 'ملغى',
    expired: 'منتهي',
    accept: 'قبول',
    reject: 'رفض',
    cancel: 'إلغاء',
    reason: 'سبب الإلغاء',
    reserved: 'الوزن المحجوز',
    available: 'السعة المتاحة',
    offered: 'السعة المعروضة',
    expires: 'ينتهي في',
    counterparty: 'الطرف الآخر',
    timeline: 'الحالة',
    view: 'عرض الحجز',
    back: 'العودة إلى الحجوزات',
    capacityNotice: 'تُحجز السعة فقط بعد القبول.',
  },
} satisfies Record<Locale, Record<string, string>>;

export type BookingStatus =
  'proposed' | 'accepted' | 'rejected' | 'cancelled' | 'expired';

export function bookingStatusLabel(locale: Locale, status: BookingStatus) {
  return bookingCopy[locale][status];
}
